### ISSUE TITLE
Play District 21

### ISSUE THREAD

**Issue by benauca** [benauca/district-21#4]
**EPIC Description**
---

**AS** PLAYER

**I WANT** to play on district 21

**SO THAT** I have a fun time

**User Stories**
---

Include a list with the User Stories 

 - [ ] **#1 CI/CD workflows**
 - [ ] **#5 Define Struct capacbilities**
 - [ ] **#6 Create API Rest Definition**
